library(tximportData)
library(tximport)
library(rhdf5)
library(dplyr)
library(venn)
library(reshape2)
library(tidyr)

# Fill in the hosts in the vector in the following line, in the order they're found in the directory
host_names <- c("Chives", "Medicago", "Nicotiana", "Tomato")

# Input directory containing tsv files generated by kallisto
input_dir <- ""
path_out <- ""
files <- list.files(path=input_dir, pattern="*.tsv", full.names=TRUE, recursive=FALSE)

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
head(txi.kallisto$counts)

n = length(host_names)
sampleTable <- data.frame(condition = factor(rep(host_names, each = 3)))
rownames(sampleTable) <- colnames(txi.kallisto$counts)

############################################################################################
# Quantile read normalization 
quantile_normalisation <- function(df){
  df_rank <- apply(df,2,rank,ties.method="min")
  df_sorted <- data.frame(apply(df, 2, sort))
  df_mean <- apply(df_sorted, 1, mean)
  
  index_to_mean <- function(my_index, my_mean){
    return(my_mean[my_index])
  }
  
  df_final <- apply(df_rank, 2, index_to_mean, my_mean=df_mean)
  rownames(df_final) <- rownames(df)
  return(df_final)
}
normalized_counts <- quantile_normalisation(counts(dds))
colnames(normalized_counts) <- as.vector(sampleTable[,1])

############################################################################################

mean_expression_list <- data.frame(rownames(normalized_counts))
j <- 1
for(host in host_names)
{
  print(host)
  k <- j + 2
  replicate_set <- as.data.frame(normalized_counts[,j:k])
  colnames(replicate_set) <- c("R1", "R2", "R3")
  replicate_set <- mutate(.data = replicate_set, mean = apply(replicate_set[,1:3],1,mean,na.rm=TRUE))
  mean_expression_list <- cbind(mean_expression_list, replicate_set[4])
  j <- j + 3
}
rownames(mean_expression_list) <- mean_expression_list[,1]
mean_expression_list = subset(mean_expression_list[-c(1)])
colnames(mean_expression_list) <- host_names
write.csv(mean_expression_list, file = paste(path_out, "mean_expression_list.csv", sep=""))

n = length(host_names)  
checking_matrix <- expand.grid(replicate(n, 0:1, simplify = FALSE))
colnames(checking_matrix) <- host_names

############################################################################################
# ANOVA test on normalized reads, to determine which genes have variation, and which ones don't.
C <- 10

p.anova <- c()
p.anova <- NULL
for (i in 1:nrow(normalized_counts))
{
  m <- as.numeric(which.max(mean_expression_list[i,]))
  if(mean_expression_list[i,m] < C)
  {
    p.anova <- append(p.anova, NA)
  }
  else
  {
  test_set <- as.data.frame(t(rbind(normalized_counts[i,], c(rep(host_names, each = 3)))))
  colnames(test_set) <- c("Expression", "Host")
  p.anova <- append(p.anova, summary(aov(formula = Expression ~Host, data = test_set))[[1]][[1,"Pr(>F)"]])
  }
}
p.anova_adj <- p.adjust(p.anova, method = "BH")

############################################################################################
# statistical tests to determine differences in expression between triplicates
# output = binary expr matrix
p <- c()
p <- NULL
for (i in 1:nrow(normalized_counts))
{
  m <- as.numeric(which.max(mean_expression_list[i,]))
  mm <- m*3-2
  if(mean_expression_list[i,m] < C
     ||
     p.anova_adj[i] > 0.05) 
  {
    p <- append(p, rep(c(NaN), each = n))
  }
  else
  {
    for (j in 1:length(host_names))
    {
      jj <- j*3-2
      if(length(unique(as.numeric(normalized_counts[i,jj:(jj+2)]))) == 1)
      {
        normalized_counts[i,jj] <- as.numeric(normalized_counts[i,jj]) + 0.000001
      }
      p <- append(p, t.test(x = normalized_counts[i,mm:(mm+2)], y = normalized_counts[i,jj:(jj+2)], alternative = "greater")$p.value)
    }  
  }  
}

p.df <- as.data.frame(matrix(p, ncol=length(host_names), byrow = TRUE), stringsAsFactors=FALSE)
head(p.df, n = 50)
nrow(p.df)
length(p)

p[p == 0.5] <- NaN
p_adj <- p.adjust(p, method = "BH")
p_adj.df <- as.data.frame(matrix(p_adj, ncol=length(host_names), byrow = TRUE), stringsAsFactors=FALSE)


############################################################################################
# Compare adjusted p-values and mean expressions per sample

FD <- 4

binary_expr_matrix <- t(data.frame(host_names))

de_comp <- c()
de_comp <- NULL
for (i in (1:as.numeric(nrow(mean_expression_list)))) 
{
  m <- as.numeric(which.max(mean_expression_list[i,]))
  for (j in 1:n) 
  {
    if (as.numeric(mean_expression_list[i,m]) < C)
    {
      de_comp <- append(de_comp, rep(c("0"), each = n))
      break
    }
    else
    {
      if (p.anova_adj[i] > 0.05)
      {
        de_comp <- append(de_comp, rep(c("1"), each = n))
        break
      }
      else
      {
        if
        (
        as.numeric(mean_expression_list[i,m])/as.numeric(mean_expression_list[i,j])>FD && 
        p_adj.df[i,j]<0.05)
        {
          de_comp <- append(de_comp, as.numeric(0))
        }
        else 
        {
        de_comp <- append(de_comp, as.numeric(1))
        }
      }
    }
  }
  binary_expr_matrix <- rbind(binary_expr_matrix, de_comp)
  de_comp <- NULL
}

colnames(binary_expr_matrix) <- host_names
binary_expr_matrix = binary_expr_matrix[-1,]
rownames(binary_expr_matrix) <- rownames(mean_expression_list)
write.csv(binary_expr_matrix, file = paste(path_out, strain, "_binary_matrix.tsv", sep=""))

############################################################################################
# Compare the binary expression matrix with the checking matrix to categorize significant differences in expression

host_venn_counts <- c()
for(i in 1:nrow(checking_matrix))
  {
  host_comp <- NULL
  for (j in 1:nrow(binary_expr_matrix)) 
    {
    if (toString(checking_matrix[i,]) == toString(binary_expr_matrix[j,])) 
      {
      host_comp <- rbind(host_comp, mean_expression_list[j,])
      }
    }
  print(paste("Round", i, nrow(host_comp), sep=" "))
  print(checking_matrix[i,])
  if (is.null(dim(host_comp)) == TRUE)
  {
    host_venn_counts <- append(host_venn_counts, 0)
  }
  else
  {
    host_venn_counts <- append(host_venn_counts, nrow(host_comp))
  }
  print(head(host_comp))
  write.csv(host_comp, file = paste(path_out, strain, "_", "host_combination_", i, ".csv", sep=""))
}

############################################################################################
# Venn Diagram
host_venn_counts
host_venn <- venn(x = n, counts = host_venn_counts, zcolor = "style", snames = rev(colnames(mean_expression_list))
                  , ilcs = 1.5, sncs = 1.5, box = FALSE)
